### ISSUE TITLE
Min-Width not working correctly

### ISSUE THREAD

**Issue by JonasPfeifer05** [JonasPfeifer05/ChatAppFX#12]
In the branch JP/resizeable I have made the first screen resizeable. The start width should be, as it stands in scene builder, 300px. So the Min width is also set to 300px. But the user is still able to resize the window and make it slightly smaller breaking it. IDK why this happens.
I also saw, that when listening and printing the width of the window, it doenst print when you resize it in the part that is below the min width.
Do you know why this could happen?

**Comment by oliverpk2000** [comment]
ngl it feels like it's trying to gaslight me. Everything is defined to shrink only to 300px but it keeps going?
I though it could have been this:
![image](https://github.com/JonasPfeifer05/ChatAppFX/assets/60604086/261ec0be-fa83-490b-86ee-bed4637e5ac7)
because its defined to use the computed size, so I changed it to this:
![image](https://github.com/JonasPfeifer05/ChatAppFX/assets/60604086/febbbf5c-fb2e-43d6-9203-3590646e1577)
but the result is the same:
![image](https://github.com/JonasPfeifer05/ChatAppFX/assets/60604086/e5219b86-4dfb-4ef9-9f3b-f2268fb6348e)
the change I made was in the definition of the vbox, but it doesn't work in the anchor pane either. I don't really have anymore ideas on how to solve this.

**Comment by oliverpk2000** [comment]
I found this stackoverflow post:
https://stackoverflow.com/questions/63868544/how-to-make-javafx-stage-resizable-only-in-height
but the suggested solution is already implemented: 
![image](https://github.com/JonasPfeifer05/ChatAppFX/assets/60604086/b991acb8-ce28-4a55-8ece-c5dab7e47007)
theoretically, this should make the user only be able to make the scene bigger, but it doesn't work

**Comment by oliverpk2000** [comment]
I am going clinically insane

**Comment by oliverpk2000** [comment]
This seems to be a bug in javafx:
https://bugs.openjdk.org/browse/JDK-8187899
the workaround mentioned (setting min size after stage.show()) doesn't work in our case:
![image](https://github.com/JonasPfeifer05/ChatAppFX/assets/60604086/f1f69319-e580-45bb-86ac-5761742d66bd)
![image](https://github.com/JonasPfeifer05/ChatAppFX/assets/60604086/2715091a-1abb-4184-b9d3-9343c1f6fbb6)
for reference, this is what it's supposed to look like:
![image](https://github.com/JonasPfeifer05/ChatAppFX/assets/60604086/41024cbe-7c92-4271-9cc8-b198ba50894c)

**Comment by oliverpk2000** [comment]
unresolvable, I'll reopen if the javafx team resolves this issue on their end. -opk
